=== politecnicojic2022-santiago/HechosHistoricos/HechosHistoricos.dtd
<!ELEMENT hechos_historicos (hecho)+>
<!ATTLIST hechos_historicos version CDATA #FIXED '1.1'
                            clave NMTOKEN #REQUIRED>
<!ATTLIST hechos_historicos xml:lang (es|en) CDATA #REQUIRED>
<!ELEMENT hecho (fecha, epoca*, PersonajeDestacado*, fechaRelevante)?>
<!ATTLIST hecho descripcion CDATA #IMPLIED
                autor CDATA #FIXED 'oscar'>
<!ELEMENT epoca (EPOCA1|EPOCA2)>
<!ELEMENT EPOCA1 (#PCDATA)>
<!ELEMENT EPOCA2 (#PCDATA)>
<!ELEMENT PersonajeDestacado ANY>
<!ATTLIST PersonajeDestacado paisOrigen (FRANCIA|ESPAÑA|ALEMANIA|JAPON|EEUU) #REQUIRED
                             cedula ID #IMPLIED
                             cedulaHermano IDREF #IMPLIED
                             cedulasPrimos IDREFS #IMPLIED>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT FechaNacimiento (#PCDATA)>
<!ELEMENT fecha (#PCDATA|formatoFecha)*>
<!ELEMENT formatoFecha (dia, mes, año)>
<!ELEMENT fechaRelevante EMPTY>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT año (#PCDATA)>

=== politecnicojic2022-santiago/HechosHistoricos/HechosHistoricos.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hechos_historicos SYSTEM "HechosHistoricos.dtd">

<hechos_historicos version="1.1" clave="FDHGFGDS" xml:lang="es">
    <hecho>
        <fecha>
            <formatoFecha>
                <dia>1</dia>
                <mes>1</mes>
                <año>2022</año>
            </formatoFecha>
        </fecha>
        <epoca>
            <EPOCA1></EPOCA1>
        </epoca>
        <PersonajeDestacado paisOrigen="ESPAÑA" cedulasPrimos="cedula1 cedula2">
            Test persona <Nombre></Nombre> y fecha de nacimiento: <FechaNacimiento></FechaNacimiento>
        </PersonajeDestacado>
        <fechaRelevante/>
    </hecho>
    <hecho descripcion="text" autor="oscar">
        <fecha>
            2022-10-09
        </fecha>
        <epoca>
            <EPOCA1></EPOCA1>
        </epoca>
        <epoca>
            <EPOCA2></EPOCA2>
        </epoca>
        <PersonajeDestacado paisOrigen="ALEMANIA" cedula="cedula1"></PersonajeDestacado>
        <PersonajeDestacado paisOrigen="EEUU" cedula="cedula2" cedulaHermano="cedula1"></PersonajeDestacado>
        <fechaRelevante/>
    </hecho>
</hechos_historicos>
