=== politecnicojic2022-santiago/HechosHistoricos/Marcadores.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="marcadores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo"></xs:element>
                <xs:element name="pagina" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"></xs:element>
                            <xs:element name="url" type="xs:string"></xs:element>
                            <xs:element name="aÃ±o">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="2000"/>
                                        <xs:maxInclusive value="2020"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tipo_pagina" maxOccurs="1" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="educativa"/>
                                        <xs:enumeration value="deportiva"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="correo" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ssl" type="xs:boolean" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== politecnicojic2022-santiago/HechosHistoricos/Marcadores.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="Marcadores.xsl" ?>
<!--<marcadores xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="Marcadores.xsd">-->
<marcadores autor="Oscar">
    <titulo>Los marcadores de medellin</titulo>
    <pagina ssl="false">
        <nombre>Abrirllave</nombre>
        <descripcion>Tutoriales de informática.</descripcion>
        <url fuente="periodico">http://www.abrirllave.com/</url>
        <año>2000</año>
        <tipo_pagina>educativa</tipo_pagina>
        <correo>oscar@gmail.com</correo>
    </pagina>
    <pagina ssl='false'>
        <nombre>Wikipedia</nombre>
        <descripcion>La enciclopedia libre</descripcion>
        <url fuente="revista">http://www.wikipedia.org/</url>
        <año>2005</año>
        <tipo_pagina>deportiva</tipo_pagina>
    </pagina>
    <pagina ssl="false">
        <nombre>W3C</nombre>
        <descripcion>Word Wide Web Consortium.</descripcion>
        <url fuente="el colombiano">http://www.w3.org/</url>
        <año>2020</año>
    </pagina>
</marcadores>
